name: Deploy to cPanel
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.4

      - name: 🛠️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🏗️ Generate static files
        run: pnpm run generate
        env:
          NODE_ENV: production
          API_URL: ${{ secrets.API_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}

      - name: 🔄 Prepare deployment files
        run: |
          # Create dist directory if it doesn't exist
          mkdir -p dist

          # Copy backend directory
          cp -r backend dist/

          # Create .htaccess for proper routing
          cat > dist/.htaccess << 'EOL'
          <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteBase /

              # If requested resource exists as a file or directory
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d

              # Handle all backend requests (API, storage, pixel-tracker, etc)
              RewriteRule ^(api|backend|storage|pixel-tracker) backend/public/$1 [L]

              # For all other routes, redirect to index.html
              RewriteRule ^(.*)$ index.html [L]
          </IfModule>

          # PHP settings
          <IfModule mod_php8.c>
              php_value upload_max_filesize 64M
              php_value post_max_size 64M
              php_value max_execution_time 300
              php_value max_input_time 300
          </IfModule>

          # Security headers
          <IfModule mod_headers.c>
              Header set X-XSS-Protection "1; mode=block"
              Header set X-Frame-Options "SAMEORIGIN"
              Header set X-Content-Type-Options "nosniff"
              Header set Referrer-Policy "strict-origin-when-cross-origin"
              Header set Permissions-Policy "geolocation=(), microphone=(), camera=()"
          </IfModule>

          # Enable Gzip compression
          <IfModule mod_deflate.c>
              AddOutputFilterByType DEFLATE text/plain
              AddOutputFilterByType DEFLATE text/html
              AddOutputFilterByType DEFLATE text/xml
              AddOutputFilterByType DEFLATE text/css
              AddOutputFilterByType DEFLATE application/xml
              AddOutputFilterByType DEFLATE application/xhtml+xml
              AddOutputFilterByType DEFLATE application/rss+xml
              AddOutputFilterByType DEFLATE application/javascript
              AddOutputFilterByType DEFLATE application/x-javascript
              AddOutputFilterByType DEFLATE application/json
          </IfModule>

          # Browser caching
          <IfModule mod_expires.c>
              ExpiresActive On
              ExpiresByType image/jpg "access plus 1 year"
              ExpiresByType image/jpeg "access plus 1 year"
              ExpiresByType image/gif "access plus 1 year"
              ExpiresByType image/png "access plus 1 year"
              ExpiresByType image/svg+xml "access plus 1 year"
              ExpiresByType text/css "access plus 1 month"
              ExpiresByType application/javascript "access plus 1 month"
          </IfModule>
          EOL

          # Ensure storage directory exists and has correct permissions
          mkdir -p dist/backend/storage/{app,framework,logs}
          mkdir -p dist/backend/storage/framework/{cache,sessions,views}
          chmod -R 775 dist/backend/storage

          # Create storage symlink if needed
          if [ ! -d "dist/backend/public/storage" ]; then
            ln -s ../storage/app/public dist/backend/public/storage
          fi

      - name: 📂 Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            **/backend/storage/framework/cache/**
            **/backend/storage/framework/sessions/**
            **/backend/storage/framework/views/**
            **/backend/storage/logs/**
            **/backend/bootstrap/cache/**
            **/.nuxt/**
            **/.output/**
            **/dist/**
            **/.DS_Store
            **/thumbs.db